vue-pivottable/vue3-pivottable

- src/components/pivottable-ui/VFilterBox.vue
> refactor: refactoring VFilterBox.vue

- src/assets/style.css
- src/components/pivottable-ui/VDragAndDropCell.vue
- src/components/pivottable-ui/VDraggableAttribute.vue
- src/components/pivottable-ui/VPivottableUi.vue
- src/composables/usePropsState.js
> Refactor/dragndrop: props명, coumputed 수정 & 드래그 이벤트 데이터 갱신

- src/assets/style.css
- #36 
- 문제되는 스타일 일단 주석처리만 했습니다. 드래그시 필터박스 닫히게 하는 부분이 대체되고 난후에 해당 코드를 완전히 제거하면 되지 않을까 싶습니다!
> fix: modify sortable-chosen style

- src/components/pivottable-ui/VAggregatorCell.vue
- src/components/pivottable-ui/VDropdown.vue
- src/components/pivottable-ui/VFilterBox.vue
> fix: fix initial value in VDropDown.vue

- src/components/pivottable-ui/VDragAndDropCell.vue
- src/components/pivottable-ui/VPivottableUi.vue
#39 필터박스 선택/해제 반영 안됨 문제 -> 오타 수정
> fix: unselectedFilterValues 오타 수정 #39

- src/components/pivottable-ui/VFilterBox.vue
- src/components/pivottable-ui/VPivottableUi.vue
- src/composables/usePivotUiState.js
- #42 
- UI에서 props 데이터 변경 확인을 위해서 화면에 추가한 테스트용 코드들 삭제
> fix: fix onMoveFilterBoxToTop args type change to string, #42 close

- package.json
- packages/lazy-table-renderer/LICENSE
- packages/lazy-table-renderer/package.json
- packages/lazy-table-renderer/src/index.js
- packages/lazy-table-renderer/vite.config.js
- pnpm-lock.yaml
- src/components/pivottable-ui/VPivottableUi.vue
- 라이센스 파일 수정 
- package.json 수정 (스크립트 수정, 사이트 이펙트 추가, 디펜더시 수정, 빌드 파일 수정 등)
> chore: add LICENSE and update package.json

- package.json
- pnpm-lock.yaml
- package.json 충돌난 부분 수정 잘못해서 다시 수정했습니다
> fix: build error

- package.json
> chore: update v1.0.5

- .releaserc.json
> ci: update .releaserc.json

- .github/workflows/release-lazy-table-renderer.yml
- .github/workflows/release-vue-pivottable.yml
- .releaserc.json
- main 브랜치 룰 보호 우회를 위한 semantic-release 인증용 App을 설치하고 사용
> chore: update release and add app

- .releaserc.json
- @semantic-release/github:  pr 생성 관련 설정 제거 
- @semantic-release/git : 변경사항 반영할 수 있게 추가
> fix: add missing @semantic-release/git

- .github/workflows/release-lazy-table-renderer.yml
- .github/workflows/release-vue-pivottable.yml
아래 레포에서 테스트한 내용 기반으로 워크플로우 수정했습니다.
- https://github.com/Seungwoo321/test-pr-origin
> chore: update workflows

- src/composables/useMaterializeInput.js
- src/helper/utilities.d.ts
- tsconfig.json
- vite.config.ts
#122  #120 
- strictNullChecks
- strictBindCallApply
- strictPropertyInitialization
- noImplicitAny
> 빌드 에러 수정 & 타입스크립트 규칙 세팅

- eslint.config.js
- package.json
- pnpm-lock.yaml
typescript-lint 설치 및 환경설정 업데이트
> chore(lint): add typescript-lint #142

- eslint.config.js
- pnpm-lock.yaml
- src/components/pivottable-ui/VDragAndDropCell.vue
- src/components/pivottable-ui/VDraggableAttribute.vue
- src/components/pivottable-ui/VDropdown.vue
- src/components/pivottable-ui/VFilterBox.vue
- src/components/pivottable-ui/VRendererCell.vue
- src/composables/useProvideFilterbox.ts
작업 파일(이슈 #156, #157, #158, #159, #160 참고)
- `VFilterBox.vue`
- `VDraggableAttribute.vue`
- `VDragAndDropCell.vue`
- `VDropDown.vue`
- `VRendererCell.vue `
> 피벗테이블 UI .vue 컴포넌트 타입스크립트 적용

- .github/workflows/release.yml
Adding debug output to validate secret lengths
> chore: debug secrets configuration

- .github/workflows/release.yml
Adding validation to check private key format
> chore: validate private key format

- .github/workflows/release.yml
> chore: verify app id

- packages/plotly-renderer/package.json
> chore: release v1.1.4

- .changeset/test-lazy-table-release.md
릴리즈 프로세스 전체 흐름을 최종 검증하기 위한 테스트 PR입니다.
- lazy-table-renderer에 대한 테스트 changeset 추가
1. PR 머지 → develop 브랜치 워크플로우 실행
2. 베타 버전 생성 및 배포 (beta 태그)
3. develop → main PR 자동 생성 또는 업데이트
4. main 머지 후 릴리즈 워크플로우 실행
5. 정식 버전 배포 (latest 태그)
6. 브랜치 동기화
- 베타 버전이 올바른 태그로 배포되는지
- 릴리즈 브랜치가 정상 생성되는지
- 정식 버전이 latest 태그로 배포되는지
- develop/main 브랜치 동기화가 정상적으로 이루어지는지
> test: lazy-table-renderer 릴리즈 프로세스 최종 검증

- .changeset/workflow-retry.md
워크플로우 npm 배포 중복 오류 해결을 위한 changeset 추가
> chore: 워크플로우 재실행을 위한 changeset 추가
