vue-pivottable/vue3-pivottable

.github/workflows/release-vue-pivottable.yml
.releaserc.json

ci: add workflows

---

.github/workflows/release-plotly-renderer.yml
packages/plotly-renderer/.releaserc.json
packages/plotly-renderer/package.json

- 버전 업데이트 및 태그 생성 v2.0.1
- release-plotly-renderer.yml 작성
- plotly-renderer/.releaserc.json 작성

chore: add plotly-renderer ci config

---

.github/workflows/release-lazy-table-renderer.yml
.github/workflows/release-vue-pivottable.yml
.github/workflows/sync-vue-pivottable.yml

- 기존 main 브랜치의 워크플로우를 release 로 변경하고 pr 요청 추가
- 새로운 main 브랜치의 워크플로우 생성 (release브랜치에 변경사항 업데이트)

ci: remove app token and add pr workflows

---

src/composables/usePropsState.ts

usePropsState.js → usePropsState.ts로 TypeScript 마이그레이션
- 기존 JS 파일 삭제
- helper import 경로 @ alias로 복구
- 빌드 경고/에러 0건까지 반복적으로 수정 및 테스트 완료
- 문서(reference/*)는 커밋 대상에서 제외
Closes #이슈번호(필요시)

feat(composables): usePropsState TypeScript 마이그레이션

---

.github/workflows/release.yml

Switching from tibdex/github-app-token to actions/create-github-app-token for better compatibility

fix: use official GitHub App token action

---

.github/workflows/release.yml

Testing if private key can generate JWT correctly

chore: test JWT generation

---

.github/workflows/release.yml

Testing private key validation

chore: validate private key format

---

.github/workflows/release.yml

Debugging private key format issue

chore: debug private key format

---

.changeset/fix-release-workflow.md
.github/workflows/release.yml

프로덕션 배포 워크플로우가 release 브랜치에서 실행되도록 수정하고, 베타와 프로덕션이 동일한 배포 로직을 사용하도록 통일했습니다.
- release.yml에서  사용하도록 변경
- npm 배포 전 release 브랜치로 checkout하도록 수정
- 베타와 프로덕션 배포가 동일한 스크립트 사용
1. 베타 테스트는 성공하지만 프로덕션 배포는 실패하는 문제
2. 베타와 프로덕션이 다른 배포 로직을 사용하여 베타 테스트의 의미가 없던 문제
3. 프로덕션 배포가 main 브랜치에서 직접 실행되던 문제

fix: 프로덕션 배포가 release 브랜치에서 실행되도록 수정

---

.changeset/test-sub-package-only.md
.github/workflows/release-branch.yml
.github/workflows/release.yml

- : release 브랜치에서 실행되는 워크플로우 추가
- : release 브랜치 생성만 담당하도록 수정
1. **main 브랜치 (release.yml)**
- 베타 버전 확인
- release/vX.X.X 브랜치 생성
- 베타 버전 제거
2. **release 브랜치 (release-branch.yml)**
- npm 배포
- GitHub Release 태그 생성
- develop 브랜치로 자동 머지
- main 브랜치로 PR 생성
- lazy-table-renderer만 업데이트하는 changeset 포함
- 하위 패키지만 변경될 때도 정상적으로 동기화되는지 확인
- 하위 패키지만 업데이트되는 경우에도 동기화 작업이 정상적으로 수행됨
- release 브랜치에서 모든 배포 관련 작업이 처리됨

feat: release 브랜치 워크플로우 분리

---

.changeset/test-release-workflow.md
packages/lazy-table-renderer/package.json
packages/plotly-renderer/package.json
scripts/release-packages.cjs

베타 버전이 없는(changeset이 없는) 패키지는 빌드/배포를 시도하지 않도록 개선
- 베타 버전 체크 로직 추가
- 베타 버전이 없는 패키지는 스킵 (불필요한 빌드 방지)
- plotly-renderer: clean 스크립트 추가 (`rimraf dist`)
- lazy-table-renderer: clean 대상 수정 (lib → dist)
- 모든 패키지의 빌드 전에 clean 실행
- 이전 빌드 잔재로 인한 문제 방지
1. changeset이 없는 패키지의 불필요한 빌드 시도 제거
2. 이전 dist가 남아있어서 빌드 실패해도 배포되는 문제 해결
3. 빌드 실패 시 changeset이 정상적으로 유지되도록 보장

fix: 베타 버전이 있는 패키지만 빌드/배포하도록 개선

---

.changeset/fix-plotly-beta-version.md
.github/workflows/release.yml

베타 버전 제거 시 중복된 베타 suffix를 모두 제거하도록 개선
plotly-renderer가 잘못된 작업으로 인해 베타가 4번 붙은 상태:
`2.0.1-beta.111-beta.222-beta.333-beta.444`
release.yml의 sed 명령어 수정:
- 기존: `sed 's/-beta.*//'`
- 수정: `sed 's/-beta.*$//'`
첫 번째 `-beta`부터 문자열 끝까지 모두 제거하여 깨끗한 버전 번호만 남김
`2.0.1-beta.111-beta.222-beta.333-beta.444` → `2.0.1`

fix: 중복된 베타 버전 suffix 제거 로직 개선

---

.changeset/fix-plotly-beta-latest.md

npm에 잘못된 베타 버전이 latest 태그로 배포된 문제를 수정하기 위한 changeset 추가
- 현재 npm latest: `@vue-pivottable/plotly-renderer@2.0.2-beta.1750376710-beta.1750377441`
- 베타 버전이 production latest 태그로 배포됨
- changeset을 추가하여 새로운 patch 버전 릴리스
- 정상적인 버전 번호로 latest 태그 업데이트
- develop 머지 → `2.0.3-beta.xxx` 생성
- main 머지 → `2.0.3` 정식 버전으로 latest 태그 업데이트

fix: plotly-renderer 베타 버전 latest 태그 문제 수정

---

.changeset/test-beta-tag-fix.md
scripts/release-packages.cjs

베타 버전이 latest 태그로 배포되는 문제를 해결하기 위해 npm 태그를 환경 변수로 제어하도록 개선
- develop 브랜치에서 베타 버전을 배포했는데 latest 태그로 배포됨
- 결과적으로 `npm install @vue-pivottable/plotly-renderer` 시 베타 버전이 설치됨
- `RELEASE_TAG` 환경 변수로 npm 배포 태그 지정
- develop 브랜치: `RELEASE_TAG=beta`로 베타 태그 배포
- main/release 브랜치: 기본값 `latest` 태그로 배포
```bash
RELEASE_TAG=beta node scripts/release-packages.cjs
```
```bash
node scripts/release-packages.cjs
```
- develop: 베타 버전은 베타 태그로만 배포
- main: 정식 버전은 latest 태그로 배포
- 사용자는 `npm install`로 안정된 버전만 받음

fix: npm 배포 시 태그를 환경 변수로 제어하도록 개선

---

.changeset/fix-beta-release-complete.md
.changeset/fix-develop-beta-issues.md
.github/workflows/release-develop.yml
package.json
packages/plotly-renderer/package.json

develop 브랜치의 현재 문제와 향후 발생 방지를 위한 워크플로우 개선을 한 번에 해결합니다.
- ✅ 베타 버전 중복 제거: `1.1.5-beta.xxx-beta.yyy` → `1.1.5-beta.yyy`
- ✅ plotly-renderer의 peerDependencies 복원: `^1.1.5-beta.xxx` → `^1.1.4`
- ✅ changeset 적용 시 package.json 백업
- ✅ 베타 버전 생성 후 peerDependencies만 원래 버전으로 복원
- ✅ 별도 커밋으로 peerDependencies 수정사항 기록
```bash
cp package.json package.json.backup
pnpm changeset version
npm version ${VERSION}-beta.${TIMESTAMP}
git commit -m "chore: prepare beta release"
git commit -m "fix: restore peerDependencies to prevent beta version pollution"
```
- 베타 버전이 다른 패키지의 의존성에 전파되지 않음
- 깔끔한 히스토리 (두 개의 명확한 커밋)
- 향후 동일한 문제 발생 방지

fix: 베타 릴리즈 프로세스 종합 개선

---

.changeset/restore-beta-versions.md
package.json
packages/lazy-table-renderer/package.json
packages/plotly-renderer/package.json

develop 브랜치가 정식 버전으로 잘못 업데이트된 것을 베타 버전으로 복구합니다.
PR #242 병합 과정에서 워크플로우가 제대로 작동하지 않아 develop 브랜치가 정식 버전이 되었습니다:
- vue-pivottable: 1.1.5 (정식)
- plotly-renderer: 2.0.6 (정식)
- lazy-table-renderer: 1.1.6 (정식)
모든 패키지를 베타 버전으로 변경:
- vue-pivottable: 1.1.5-beta.1750391874
- plotly-renderer: 2.0.6-beta.1750391874
- lazy-table-renderer: 1.1.6-beta.1750391874
**develop 브랜치는 항상 베타 버전을 유지해야 합니다.**
이 PR을 머지한 후에는 워크플로우가 정상적으로 작동하는지 확인이 필요합니다.

fix: develop 브랜치를 베타 버전으로 긴급 복구

---

.changeset/fix-peer-dependencies.md
packages/plotly-renderer/package.json

PR #238의 CI 체크 실패를 해결합니다.
PR #238 (develop → main)의 모든 체크가 실패:
```
ERR_PNPM_OUTDATED_LOCKFILE Cannot install with "frozen-lockfile"
specifiers in the lockfile ({..."vue-pivottable":"^1.1.4"...}) 
don't match specs in package.json ({..."vue-pivottable":"^1.1.5"...})
```
- plotly-renderer의 peerDependencies가 `^1.1.5`를 요구
- 하지만 1.1.5는 아직 정식 릴리즈되지 않음 (베타 버전만 존재)
- lockfile은 1.1.4를 참조하고 있어 불일치 발생
- plotly-renderer의 peerDependency를 `^1.1.4`로 수정
- 실제 존재하는 최신 정식 버전을 참조하도록 변경
- PR #238의 CI 체크가 통과할 수 있게 됨
- develop → main 릴리즈 프로세스가 정상적으로 진행 가능

fix: peerDependencies 버전 수정으로 PR #238 CI 실패 해결

---

.changeset/fix-pr238-ci.md
packages/lazy-table-renderer/package.json
packages/plotly-renderer/package.json

PR #238 (develop → main)의 CI 체크 실패를 해결합니다.
PR #238의 모든 CI 체크가 다음 오류로 실패:
```
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile"
specifiers in the lockfile ({"vue-pivottable":"^1.1.4"}) 
don't match specs in package.json ({"vue-pivottable":"^1.1.5"})
```
1. plotly-renderer의 peerDependencies가 `vue-pivottable: ^1.1.5`를 요구
2. 하지만 버전 1.1.5는 아직 정식 릴리즈되지 않음 (베타 버전만 존재)
3. pnpm lockfile은 최신 정식 버전인 1.1.4를 참조
4. CI 환경의 `--frozen-lockfile` 옵션으로 인해 불일치 감지 시 실패
- plotly-renderer의 peerDependencies를 `^1.1.4`로 수정
- 실제 존재하는 최신 정식 버전을 참조하도록 변경
이 PR이 머지되면 PR #238의 CI가 정상적으로 통과할 것입니다.

fix: PR #238 CI 실패 해결

---

.changeset/test-beta-timestamp-replacement.md
.github/workflows/release-develop.yml

- **develop 브랜치**: 베타 버전들 존재 (1.1.6-beta.xxx, 2.0.7-beta.xxx, 1.1.7-beta.xxx)
- **main PR #247**: 존재하지만 아직 승인/머지 안됨
- **추가 changeset**: vue-pivottable과 plotly-renderer 변경
```bash
ensure_beta_version() {
if [[ "$version" == *"-beta."* ]]; then
base_version=$(echo "$version" | sed 's/-beta\..*//') 
echo "${base_version}-beta.${timestamp}"
else
echo "${version}-beta.${timestamp}"
fi
}
```
| 패키지 | 현재 | 예상 결과 |
|-------|------|----------|
| vue-pivottable | 1.1.6-beta.1750400546 | 1.1.7-beta.[NEW] |
| plotly-renderer | 2.0.7-beta.1750400990 | 2.0.8-beta.[NEW] |
| lazy-table-renderer | 1.1.7-beta.1750400990 | 1.1.7-beta.[NEW] (changeset 없음) |
이 시나리오는 **실제 개발 워크플로우에서 가장 흔한 상황**입니다:
1. 베타 릴리즈 후 main 승인 대기
2. 추가 개발 작업 및 changeset 추가
3. 베타 버전 업데이트

test: 베타 타임스탬프 교체 시나리오 테스트

---

.changeset/stable-release-preparation.md

main 브랜치의 Release 워크플로우 실패를 해결하기 위해 changeset을 추가합니다.
1. develop과 main 브랜치가 동기화됨
2. main 브랜치의 Release 워크플로우가 changeset 부재로 실패
3. stable 버전 배포를 위한 changeset 필요
- stable 릴리즈를 위한 changeset 파일 추가
- 모든 패키지(vue-pivottable, lazy-table-renderer, plotly-renderer)에 patch 버전 업데이트
1. 이 PR이 develop에 머지
2. 베타 버전 업데이트 및 새로운 베타 릴리즈 PR 생성/업데이트
3. 베타 릴리즈 PR이 main에 머지될 때 changeset이 포함되어 있음
4. Release 워크플로우가 정상적으로 실행되어 stable 버전 배포

chore: stable 릴리즈 준비를 위한 changeset 추가

---

.changeset/remove-develop-sync.md
.github/workflows/release.yml

- Removes the "Sync with develop" step from the release workflow to prevent version conflicts
- This step was causing merge conflicts between main (stable versions) and develop (beta versions)
- Removed lines 204-219 from `.github/workflows/release.yml`
- Added changeset documentation
The sync step was attempting to merge stable versions from main back into develop, which already has beta versions with higher timestamps. This created version conflicts that prevented successful releases.

fix: Remove develop sync step from release workflow

---

.changeset/memory-leak-fix.md
src/components/pivottable-ui/VPivottableUi.vue
src/composables/usePivotData.ts
src/composables/useProvidePivotData.ts

Fixes #270 - Critical memory leak causing memory to increase from 50MB to 881MB after 1000 refreshes.
- Deep watch creating thousands of property watchers
- Computed PivotData creating new instances on every access
- No proper cleanup in component lifecycle
- Remove `deep: true` from watch, use `immediate: true` instead
- Replace `computed` PivotData with `shallowRef` to reuse instances
- Add proper cleanup in `onUnmounted` lifecycle hook
- **94% memory reduction**: 881MB → 53MB after 1000 refreshes
- **Stable memory usage** even with continuous data updates
- **Component Key remains at 0** (no unnecessary recreations)
- Tested with 1000+ data refreshes
- Memory profiled using Chrome DevTools
- Verified with different data sizes (1k, 5k, 10k records)
None - This is a internal optimization …

fix: resolve critical memory leak in VPivottableUi component (#270)
